/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000
      thread_priority: 98

      joint_impedance_controller:
        type: rlinf_franka_controller/JointImpedanceController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

  joint_impedance_controller:
    ros__parameters:
      arm_id: fr3
      k_alpha: 0.99
      target_filter_cutoff: 30.0
      k_gains: [240.0, 240.0, 240.0, 240.0, 100.0, 60.0, 60.0]
      d_gains: [8.0, 8.0, 8.0, 4.0, 3.0, 3.0, 1.5]
      reset_speed_factor: 0.1
      command_timeout: 0.5
      max_command_error: 0.04
      command_topic: rlinf/joint_targets
      reset_topic: rlinf/reset_joint_target

  franka_robot_state_broadcaster:
    ros__parameters:
      lock_update_success: true
      lock_log_error: false
